{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# for second set of data\n",
    "import serial\n",
    "import time\n",
    "import math\n",
    "import csv\n",
    "from gekko import GEKKO\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "ser = serial.Serial(\n",
    "    port='COM6',\n",
    "    baudrate=115200,\n",
    "    timeout=1\n",
    ")\n",
    "\n",
    "# List to store results for each run\n",
    "results = {i: [] for i in range(1, 55)}  # Initialize results dict for 54 runs\n",
    "\n",
    "def send_command(command):\n",
    "    ser.reset_input_buffer()\n",
    "    ser.write(f\"{command}\\r\\n\".encode())\n",
    "    time.sleep(0.01)\n",
    "    \n",
    "    while ser.in_waiting:\n",
    "        response = ser.readline().decode().strip()\n",
    "        if response:\n",
    "            print(f\"Pico response: {response}\")\n",
    "            if response.startswith(\"MPU:\"):\n",
    "                return [float(x) for x in response[4:].split()]\n",
    "    return None\n",
    "\n",
    "def send_angles(pitch, yaw):\n",
    "    command = f\"ANGLE {pitch} {yaw}\"\n",
    "    return send_command(command)\n",
    "\n",
    "def setup_mpc():\n",
    "    m = GEKKO()\n",
    "    m.time = np.linspace(0, 2, 21)\n",
    "    \n",
    "    yaw_measured = m.CV(value=0)\n",
    "    servo_angle = m.MV(value=90)\n",
    "    \n",
    "    servo_angle.LOWER = 0\n",
    "    servo_angle.UPPER = 180\n",
    "    servo_angle.DMAX = 10\n",
    "    servo_angle.STATUS = 1\n",
    "    \n",
    "    yaw_measured.STATUS = 1\n",
    "    \n",
    "    K = 0.8\n",
    "    tau = 0.5\n",
    "    m.Equation(tau * yaw_measured.dt() == -yaw_measured + K * servo_angle)\n",
    "    \n",
    "    m.options.IMODE = 6\n",
    "    m.options.CV_TYPE = 2\n",
    "    m.options.NODES = 3\n",
    "    \n",
    "    return m, yaw_measured, servo_angle\n",
    "\n",
    "def correct_yaw_mpc(target_yaw, actual_yaw, current_servo_yaw):\n",
    "    if not hasattr(correct_yaw_mpc, 'mpc'):\n",
    "        correct_yaw_mpc.mpc, correct_yaw_mpc.yaw_cv, correct_yaw_mpc.servo_mv = setup_mpc()\n",
    "    \n",
    "    m = correct_yaw_mpc.mpc\n",
    "    yaw_cv = correct_yaw_mpc.yaw_cv\n",
    "    servo_mv = correct_yaw_mpc.servo_mv\n",
    "    \n",
    "    yaw_cv.MEAS = actual_yaw\n",
    "    yaw_cv.SP = target_yaw\n",
    "    \n",
    "    try:\n",
    "        m.solve(disp=False)\n",
    "        new_servo_yaw = float(servo_mv.NEWVAL)\n",
    "        new_servo_yaw = max(0, min(180, new_servo_yaw))\n",
    "        return new_servo_yaw\n",
    "    except:\n",
    "        print(\"MPC solution failed, using current angle\")\n",
    "        return current_servo_yaw\n",
    "\n",
    "try:\n",
    "    time.sleep(0.01)\n",
    "    ser.reset_input_buffer()\n",
    "    \n",
    "    # Read from angle_tracking_all_hr.csv\n",
    "    ########\n",
    "    # INPUT FILE HERE\n",
    "    ########\n",
    "    with open('angle_tracking_all_hr.csv', 'r') as file:\n",
    "        csv_reader = csv.DictReader(file)\n",
    "        \n",
    "        # Process each run (1-54)\n",
    "        for run in range(1, 55):\n",
    "            # Reset pitch to 25 degrees before each run\n",
    "            _ = send_angles(25, 90)  # Reset to 25 degrees pitch, neutral yaw\n",
    "            time.sleep(0.5)  # Give time for servo to reach position\n",
    "            \n",
    "            command_count = 0\n",
    "            pitch_col = f'pitch_{run}'\n",
    "            yaw_col = f'yaw_{run}'\n",
    "            \n",
    "            # Reset file pointer for each run\n",
    "            file.seek(0)\n",
    "            next(csv_reader)  # Skip header\n",
    "            \n",
    "            \n",
    "            current_servo_yaw = target_yaw\n",
    "            actual_angles = send_angles(target_pitch, current_servo_yaw)\n",
    "            \n",
    "                \n",
    "            target_pitch = float(row[pitch_col])\n",
    "            target_yaw = float(row[yaw_col])\n",
    "            \n",
    "            # Ensure angles stay within bounds\n",
    "            target_pitch = max(0, min(180, target_pitch))\n",
    "            target_yaw = max(0, min(180, target_yaw))\n",
    "            \n",
    "            current_servo_yaw = target_yaw\n",
    "            actual_angles = send_angles(target_pitch, current_servo_yaw)\n",
    "            \n",
    "            if actual_angles:\n",
    "                actual_pitch, actual_yaw = actual_angles\n",
    "                pitch_error = abs(target_pitch - actual_pitch)\n",
    "                yaw_error = abs(target_yaw - actual_yaw)\n",
    "                \n",
    "                # Store results for this run\n",
    "                results[run].append({\n",
    "                    f'pitch_{run}': target_pitch,\n",
    "                    f'measured_pitch_{run}': actual_pitch,\n",
    "                    f'err_{run}': pitch_error,\n",
    "                    f'yaw_{run}': target_yaw,\n",
    "                    f'measured_yaw_{run}': actual_yaw,\n",
    "                    f'yaw_err_{run}': yaw_error\n",
    "                })\n",
    "                \n",
    "                print(f\"Run {run} - Command {command_count + 1}\")\n",
    "                print(f\"Target angles - Pitch: {target_pitch:.2f}, Yaw: {target_yaw:.2f}\")\n",
    "                print(f\"Actual angles - Pitch: {actual_pitch:.2f}, Yaw: {actual_yaw:.2f}\")\n",
    "                print(f\"Errors - Pitch: {pitch_error:.2f}, Yaw: {yaw_error:.2f}\")\n",
    "                \n",
    "                current_servo_yaw = correct_yaw_mpc(target_yaw, actual_yaw, current_servo_yaw)\n",
    "                print(f\"Corrected servo yaw: {current_servo_yaw:.2f}\\n\")\n",
    "            \n",
    "            command_count += 1\n",
    "            time.sleep(0.01)\n",
    "\n",
    "except KeyboardInterrupt:\n",
    "    print(\"\\nOperation interrupted by user\")\n",
    "\n",
    "finally:\n",
    "    # Save all results to a single CSV\n",
    "    all_data = []\n",
    "    max_rows = 0\n",
    "    \n",
    "    # First find the maximum number of rows across all runs\n",
    "    for run in range(1, 55):\n",
    "        if results[run]:\n",
    "            max_rows = max(max_rows, len(results[run]))\n",
    "    \n",
    "    # Create the combined data\n",
    "    for i in range(max_rows):\n",
    "        row_data = {}\n",
    "        for run in range(1, 55):\n",
    "            if results[run] and i < len(results[run]):\n",
    "                row_data.update(results[run][i])\n",
    "        all_data.append(row_data)\n",
    "    \n",
    "    if all_data:\n",
    "        #########\n",
    "        # OUTPUT FILE NAME HERE\n",
    "        ########\n",
    "        filename = 'combined_results2.csv'  # Changed filename\n",
    "        fieldnames = []\n",
    "        for run in range(1, 55):\n",
    "            if results[run]:\n",
    "                fieldnames.extend(list(results[run][0].keys()))\n",
    "        \n",
    "        with open(filename, 'w', newline='') as file:\n",
    "            writer = csv.DictWriter(file, fieldnames=fieldnames)\n",
    "            writer.writeheader()\n",
    "            writer.writerows(all_data)\n",
    "            print(f\"All results saved to {filename}\")\n",
    "    \n",
    "    ser.close()\n",
    "    print(\"Serial connection closed\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
